<a href="https://colab.research.google.com/github/Murcha1990/Raiffaizen_ML_summer2023/blob/main/%D0%97%D0%B0%D0%BD%D1%8F%D1%82%D0%B8%D0%B5_8_trees/Practice_Raiff.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Практическое задание

В этом задании попрактикуйтесь обучать модель предсказывать тип опухоли в груди у женщин (доброкачественная или злокачественная).

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import confusion_matrix, roc_auc_score

### Загрузим данные для работы.

In [2]:
from sklearn.datasets import load_breast_cancer

X, y = load_breast_cancer(return_X_y=True, as_frame=True)

X.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [5]:
y

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: target, Length: 569, dtype: int64

Будем решать задачу классификации: необходимо предсказать по характеристикам новообразования в груди, является ли оно злокачественным.

### Шаг 1.  
Выведите на экран размеры матрицы объект-признак `X`, а также количество объектов каждого класса в целевой переменной `y`.

In [3]:
#your code here

X.shape

(569, 30)

In [4]:
y.value_counts()

1    357
0    212
Name: target, dtype: int64

### Шаг 2.
Разбейте данные на train и test (доля тестовых данных - 30%, random_state=42).

In [6]:
#your code here

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

### Шаг 3.

Масштабируйте данные при помощи MinMaxScaler.

P.S. Обучайте скалер (fit) только на тренировочных данных, а преобразуйте (transform) и train, и test. После масштабирования верните данные к формату pd.DataFrame.

In [ ]:
#your code here

# from sklearn.pipeline import Pipeline # лаконичный способ сделать обработку данных

# pipe = Pipeline([
#     ('OHE', OneHotEncoder(categorical_columns)),
#     ('Scaler', MinMaxScaler(numerical_columns)),
#     ('model', LogisticRegression())
# ])

In [7]:
from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler()

sc.fit(X_train)

X_train = pd.DataFrame(sc.transform(X_train), columns=X_train.columns)
X_test = pd.DataFrame(sc.transform(X_test), columns=X_test.columns)

X_train.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0     0.296244      0.277308        0.283818   0.177894         0.167807   
1     0.278123      0.225905        0.269406   0.164378         0.085638   
2     0.342769      0.144403        0.355879   0.208401         0.402319   
3     0.255595      0.223876        0.243936   0.148460         0.167509   
4     0.290367      0.457220        0.277183   0.172831         0.296858   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0          0.151976        0.067502             0.066054       0.163374   
1          0.184474        0.189597             0.139165       0.136145   
2          0.562359        0.339738             0.313121       0.490657   
3          0.117389        0.090745             0.118141       0.353444   
4          0.164681        0.069681             0.121421       0.265350   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                0.122999  ...      0.243476       0.278252         0.217071   
1                0.174179  ...      0.204006       0.285981         0.190636   
2                0.507582  ...      0.284409       0.168443         0.303035   
3                0.141323  ...      0.190118       0.265991         0.184637   
4                0.169545  ...      0.243842       0.454957         0.219053   

   worst area  worst smoothness  worst compactness  worst concavity  \
0    0.124628          0.115640           0.163881         0.173124   
1    0.101355          0.154940           0.242126         0.366172   
2    0.145296          0.364200           0.364306         0.356321   
3    0.093539          0.207437           0.128688         0.195262   
4    0.125595          0.294203           0.129905         0.116117   

   worst concave points  worst symmetry  worst fractal dimension  
0              0.218396        0.154741                 0.128009  
1              0.325762        0.095210                 0.180061  
2              0.402032        0.248768                 0.314005  
3              0.298803        0.287601                 0.122499  
4              0.260305        0.212300                 0.122838  

[5 rows x 30 columns]

### Шаг 4.
Обучите логистическую регрессию на тренировочных данных и сделайте предсказания на train и на test.

P.S. Предсказывайте и классы (назовите векторы предсказаний `pred_train`, `pred_test`), и вероятности положительного класса (`probs_train`, `probs_test`).

In [8]:
#your code here

model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [9]:
pred_train = model.predict(X_train) # предсказываем классы

pred_test = model.predict(X_test)

In [11]:
pred_train

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,

In [10]:
probs_train = model.predict_proba(X_train)[:,1] # предсказываем вер-ть положительного класса

probs_test = model.predict_proba(X_test)[:,1]

In [16]:
probs_train.round(2) # округляем ответ до 2х знаков после запятой

array([0.96, 0.94, 0.69, 0.95, 0.88, 0.49, 0.74, 0.96, 0.86, 0.79, 0.9 ,
       0.98, 0.33, 0.07, 0.34, 0.44, 0.82, 0.15, 0.95, 0.01, 0.92, 0.95,
       0.99, 0.97, 0.3 , 0.73, 0.99, 0.01, 0.99, 0.95, 0.98, 0.  , 0.95,
       0.  , 0.01, 0.98, 0.97, 0.84, 0.4 , 0.98, 0.99, 0.96, 1.  , 0.22,
       0.98, 0.96, 0.99, 0.98, 0.99, 0.16, 0.75, 0.01, 0.02, 0.94, 0.97,
       0.  , 0.95, 1.  , 0.92, 0.91, 0.84, 0.96, 0.96, 0.35, 0.1 , 0.  ,
       0.98, 0.93, 0.  , 0.92, 0.96, 0.09, 0.95, 0.29, 1.  , 0.01, 0.95,
       0.71, 0.98, 0.64, 0.28, 0.93, 0.99, 0.83, 0.04, 0.91, 0.03, 0.8 ,
       0.03, 0.98, 0.15, 0.98, 0.68, 0.06, 0.83, 1.  , 0.95, 0.97, 0.21,
       0.74, 0.97, 0.92, 0.01, 0.6 , 0.96, 0.24, 0.79, 0.98, 0.01, 0.96,
       0.99, 0.94, 0.94, 0.95, 0.71, 0.99, 0.22, 0.96, 0.91, 0.94, 0.54,
       0.99, 0.02, 0.63, 0.91, 0.98, 0.27, 0.98, 0.13, 0.01, 1.  , 0.87,
       0.09, 0.99, 0.14, 0.22, 0.96, 0.9 , 0.96, 0.72, 0.88, 0.93, 1.  ,
       0.02, 0.93, 0.39, 0.9 , 0.84, 0.89, 0.  , 0.

### Шаг 5.
Выведите на экран матрицу ошибок на train и на test, затем выведите на экран ROC-AUC на train и test.  

P.S. ROC-AUC измеряем на предсказанных вероятностях! (а не на классах)

In [17]:
#your code here

confusion_matrix(y_train, pred_train)

array([[137,  12],
       [  1, 248]])

In [18]:
confusion_matrix(y_test, pred_test)

array([[ 58,   5],
       [  1, 107]])

In [19]:
roc_auc_score(y_train, probs_train), roc_auc_score(y_test, probs_test)

# все auc (и gini) считаются по вероятностям

(0.9915366162637126, 0.9979423868312758)

### Шаг 6.
Вычислите среднее качество (ROC-AUC) модели на кросс-валидации с k=3 фолдами. Для кросс-валидации используйте все данные (X, y).

In [24]:
import sklearn

sklearn.metrics.get_scorer_names() # список всех доступных метрик

['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'completeness_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'matthews_corrcoef',
 'max_error',
 'mutual_info_score',
 'neg_brier_score',
 'neg_log_loss',
 'neg_mean_absolute_error',
 'neg_mean_absolute_percentage_error',
 'neg_mean_gamma_deviance',
 'neg_mean_poisson_deviance',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'neg_negative_likelihood_ratio',
 'neg_root_mean_squared_error',
 'normalized_mutual_info_score',
 'positive_likelihood_ratio',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'rand_score',
 'recall',
 'recall_macro',
 'recall_micro',
 'recall_samples',
 'recall_weighted',

In [30]:
#your code here

sc.fit(X)
X2 = pd.DataFrame(sc.transform(X), columns=X.columns) # масштабируем данные перед кросс-валидацией

cross_val_score(model, X2, y, cv=3, scoring='roc_auc').mean()

0.9927277953434895

### Шаг 7.

Теперь подберите гиперпараметр регуляризации `C` у логистической регрессии. Ищите `C` в диапазоне [0, 10] с шагом 0.1.

Осуществите подбор гипараметра `C` по тренировочным данным (Xtrain, ytrain).

P.S. Осуществляйте поиск при помощи GridSearchCV.

In [33]:
#your code here

params = {'C' : np.arange(0.1, 10.1, 0.1)}

gs = GridSearchCV(model, params, cv=3, scoring='roc_auc')

gs.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=LogisticRegression(),
             param_grid={'C': array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,
        1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,
        2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,
        3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,
        4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,
        5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,
        6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,
        7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,
        8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9,
       10. ])},
             scoring='roc_auc')

In [35]:
gs.best_params_, gs.best_estimator_ # уже обученная модель с наилучшим найденным С

({'C': 10.0}, LogisticRegression(C=10.0))

### Шаг 8.

С помощью логистической регрессии с наилучшим найденным `C` сделайте предсказание на тестовых данных и выведите на экран ROC-AUC на тесте.

In [36]:
#your code here

probs_best = gs.best_estimator_.predict_proba(X_test)[:,1]

In [37]:
roc_auc_score(y_test, probs_best)

0.998236331569665

### Сделайте выводы. Для этого ответьте на вопросы:

Хорошего ли качества модели удалось добиться (в терминах ROC-AUC)?

Да, качество отличное (так как почти 1).

Ноутбук вам в помощь (с предыдущих занятий):

* [Логистическая регрессия](https://colab.research.google.com/github/Murcha1990/Raiffaizen_ML_summer2023/blob/main/%D0%97%D0%B0%D0%BD%D1%8F%D1%82%D0%B8%D0%B5_5_logreg/sem5_LinearModels.ipynb)